

<?php

$apikey_source = '';

if(Mage::helper('gmapstrlocator')->getGMapAPIKey() != ''):

$apikey_source = 'http://maps.google.com/maps/api/js?key='.Mage::helper('gmapstrlocator')->getGMapAPIKey().'&sensor=false';

else :

$apikey_source = 'http://maps.google.com/maps/api/js?sensor=false';

endif;

?>

<script type="text/javascript">

var user_position_search = '';

if(typeof String.prototype.trim !== 'function') {
  String.prototype.trim = function() {
    return this.replace(/^\s+|\s+$/g, '');
  }
}

</script>

<?php if(version_compare(Mage::getVersion(), '1.9.0.0') < 0): ?>
  <script type="text/javascript" src="<?php echo $this->getJsUrl('gmapstrlocator/jquery.js'); ?>"></script>
<?php endif; ?>

<script type="text/javascript" src="<?php echo $this->getJsUrl('gmapstrlocator/jquery-ui.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl('gmapstrlocator/ui/jquery.ui.map.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl('gmapstrlocator/ui/jquery.ui.map.overlays.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl('gmapstrlocator/ui/jquery.ui.map.extensions.js'); ?>"></script>


<script type="text/javascript" src="<?php echo $apikey_source; ?>"></script>
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?libraries=places,geometry&sensor=false"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl('gmapstrlocator/googlemarkerInfobox.js'); ?>"></script>

<script type="text/javascript" src="<?php echo $this->getJsUrl('gmapstrlocator/markerwithlabel.js'); ?>"></script>


<?php

      $search_global = Mage::registry('gmap-search');
      if($search_global != ''): //show stores respective to search

      ?>

      <script type="text/javascript">
	      user_position_search = true;
	      var pgeocoder = new google.maps.Geocoder();
	      pgeocoder.geocode( { 'address': '<?php echo $search_global; ?>'}, function(results, status) {
			    if (status == google.maps.GeocoderStatus.OK) {
				    var searched_loc = results[0].geometry.location;
				    user_position_search = searched_loc;
				    findDistanceFromClientToStores(user_position_search); //find distance and call to generate list
				    jQuery('#scrollbar1').tinyscrollbar_update();
			    }
	      });

      </script>

      <?php


      endif;


    $Stores = $this->getAllStores();
    $ProdList = $this->getProductListAuto();
    $Attributes = $this->getAllAttributes();

    if($Stores){
	foreach($Stores as $key => $value){
	    $Stores[$key]['store_description'] = Mage::helper('gmapstrlocator')->getWysiwygFilter($Stores[$key]['store_description']);
	    $Stores[$key]['distance'] = 0;
	    $Stores[$key]['attributes_list'] = Mage::helper('gmapstrlocator')->listStoreAttributes($Stores[$key]['linked_attributes']);;
	}
    }

    //Config values
    $standard_lat = Mage::helper('gmapstrlocator')->getGMapStandardLatitude();
    $standard_long = Mage::helper('gmapstrlocator')->getGMapStandardLongitude();

    //direction button text
    $direction_button_text = Mage::helper('gmapstrlocator')->getDirectionButtonText();
    if($direction_button_text == ''): $direction_button_text = 'Get Direction'; endif;

    //GMap Marker Image
    $gmap_marker_image = Mage::helper('gmapstrlocator')->getGMapMarkerSrc();
    if(!Mage::helper('gmapstrlocator')->getGMapMarkerExist()): $gmap_marker_image = $this->getSkinUrl('images/gmapstrlocator/ib_icon.png'); endif;

    //GMap Hover Marker Image
    $gmap_hover_marker = $gmap_marker_image;
    if(Mage::helper('gmapstrlocator')->getGMapPopupBgprimaryExist()): $gmap_hover_marker = Mage::helper('gmapstrlocator')->getGMapPopupBgprimarySrc(); endif;


    if(Mage::helper('gmapstrlocator')->getGMapPopupBgsecondaryExist()):
	$popup_secondary_image = Mage::helper('gmapstrlocator')->getGMapPopupBgsecondarySrc();
    else:
	$popup_secondary_image =  $this->getSkinUrl('images/gmapstrlocator/map_popup_bottom.png');
    endif;


    $marker_hover_enabled = Mage::getStoreConfig('gmapstrlocator/info_popup/enable_mouseover_marker');
    $marker_numbers_enabled = Mage::getStoreConfig('gmapstrlocator/info_popup/enable_marker_numbers');
    $marker_sidebar_enabled = Mage::getStoreConfig('gmapstrlocator/info_popup/enable_sidebar_markers');

    $map_distance = Mage::helper('gmapstrlocator')->getGMapDistance();

    $list_url = Mage::helper('gmapstrlocator')->getGMapListIdentifier();
    $seo_sufix = Mage::helper('gmapstrlocator')->getGMapSeoSuffix();

    //echo "<pre>"; print_r($Stores); exit;

?>
<script src="<?php echo $this->getJsUrl('gmapstrlocator/jquery.tinyscrollbar.min.js'); ?>" type="text/javascript"></script>
<script type="text/javascript">
	jQuery(document).ready(function(){
				jQuery('#scrollbar1').tinyscrollbar();

			});
</script>



		<div class="top_title">
				<h1><?php echo Mage::helper('gmapstrlocator')->getGMapPageHeading(); ?></h1>
				<p class="head-content"><?php echo Mage::helper('gmapstrlocator')->getGMapPageSubheading(); ?></p>
		</div>

		<div id="main">
			  <!--Left Col-->
			  <div class="form">

				      <?php if(Mage::helper('gmapstrlocator')->isSearchByProductEnable()): ?>
				      <div class="field1">
					  <h3><?php echo Mage::helper('gmapstrlocator')->__('Search for Products'); ?></h3>
					  <input type="text" class="input" name="prod_search" id="prod_search">
					  <input type="button" class="button" value="<?php echo Mage::helper('gmapstrlocator')->__('Search'); ?>" name="" onclick="searchByProducts(this.value)">
				      </div>
				      <?php endif; ?>

				      <?php if(Mage::helper('gmapstrlocator')->isSearchByAddressEnable()): ?>
				      <div class="field2">
					<h3><?php echo Mage::helper('gmapstrlocator')->__('Search By Address, Zip Code, State'); ?></h3>
					<input name="s_address" id="s_address" type="text" class="input" />
					<select class="select_radius" id="store_radius" name="store-radius">
					  <option value=""><?php echo $this->__('All') ?></option>

					  <?php if($map_distance == 'km'): ?>
					    <option value="10">10 km</option>
					    <option value="20">20 km</option>
					    <option value="50">50 km</option>
					    <option value="100">100 km</option>
					    <option value="200">200 km</option>
					  <?php else: ?>
					    <option value="10">10 mile</option>
					    <option value="20">20 mile</option>
					    <option value="50">50 mile</option>
					    <option value="100">100 mile</option>
					    <option value="200">200 mile</option>
					  <?php endif; ?>

					</select>
					<input name="" type="button" class="button" value="<?php echo $this->__('Search') ?>" onclick="searchAddress();" />
				      </div>
				      <?php endif; ?>

				      <div class="field3">
					<p>&nbsp;</p>
					<a href="javascript: " onclick="clearSearchArea()" class="search-clear"><?php echo $this->__('Reset') ?></a>
				      </div>
				      <div class="clear"></div>
			    </div>
			    <!--</form>-->


			    <div class="stores" >
				<div id="scrollbar1">
					<div class="scrollbar">
					  <div class="track">
					    <div class="thumb">
					      <div class="end"></div>
					    </div>
					  </div>
					</div>

					<div class="viewport">
					    <div class="overview">
						<div class="content" id="result">


						</div>
					    </div>
					</div>
					<div class="clear"></div>

				</div>
			    </div>



			  <!--Right Col-->
			  <div class="map">
			    <div id="map_canvas" style="height:555px; " ></div>
			  </div>


			  <div style="clear:both"></div>
			  <?php if(Mage::helper('gmapstrlocator')->getGMapFilterEnable()): ?>

			      <div class="tags">

				<?php if(Mage::helper('gmapstrlocator')->getGMapFilterHeading()): ?>
				  <h3><?php echo Mage::helper('gmapstrlocator')->getGMapFilterHeading(); ?></h3>
				<?php else: ?>
				  <h3><?php echo Mage::helper('gmapstrlocator')->__('Filter by tags'); ?></h3>
				<?php endif; ?>

				<ul id="attribute-filters">

				  <li><a href="javascript: " onclick="removeAllFilters()"><?php echo Mage::helper('gmapstrlocator')->__('Show All'); ?></a></li>

				  <?php $all_attributes = Mage::helper('gmapstrlocator')->getListOfDistinctTags(); ?>
				  <?php foreach($all_attributes as $attr): ?>

				    <li id="filter-<?php echo $attr['attributes_id']; ?>">
				      <a href="javascript: " onclick="filterByAttributes(<?php echo $attr['attributes_id']; ?>)"><?php echo $attr['attributes_name']; ?></a>
				      <a href="javascript: " onclick="removeFilter(<?php echo $attr['attributes_id']; ?>)" class="close" style="display:none;" >x</a>
				    </li>

				  <?php endforeach; ?>
				</ul>
				  <div style="clear:both"></div>
			      </div>

			  <?php endif; ?>

		</div>




	<script type="text/javascript">

	var marker, i;var map;
	var locations = <?php echo json_encode($Stores); ?>;
	var destinationIcon = '<?php echo $gmap_marker_image; ?>';
	var hoverIcon = '<?php echo $gmap_hover_marker; ?>';
	var client_current_latlang = '';
	var stores_from_distances = [];
	var geocoder = new google.maps.Geocoder();


	var naddress;
	var loc='';
	var result_to = 0;
	var shortest = new Array();
	var distancecounter =1;

	var MarkerArr = new Array();
	var PopupArr = new Array();
	var filterAttributeIds = new Array();

	var is_direction_on = false;
	var is_hover_marker_change = '<?php echo $marker_hover_enabled; ?>';
	var is_marker_numbers_enable = '<?php echo $marker_numbers_enabled; ?>';
	var is_marker_sidebar_enable = '<?php echo $marker_sidebar_enabled; ?>';
	var map_config_distance		= '<?php echo $map_distance; ?>';

	function initialize() {

		      var opts = {
			      zoom: <?php echo Mage::helper('gmapstrlocator')->getGMapZoom(); ?>,
			      center: new google.maps.LatLng(<?php echo $standard_lat; ?>,<?php echo $standard_long; ?>),
			      mapTypeId: google.maps.MapTypeId.ROADMAP,

		      };
		      map = new google.maps.Map(document.getElementById('map_canvas'), opts);

		      <?php if(Mage::helper('gmapstrlocator')->isSearchByAddressEnable()): ?>
			  var input = document.getElementById('s_address');
			  var autocomplete = new google.maps.places.Autocomplete(input);
			  autocomplete.bindTo('bounds', map);
		      <?php endif; ?>

		      is_direction_on = false;
			  generateStoreList();

	}

	function clearSearchArea(){

	  //clear the field of search
	  document.getElementById('s_address').value = '';

	  //regenerate all the options
	  initialize();

	}


	function creatmarkers(i, loc_detail) {

			var marker_img = destinationIcon;
			//if(loc_detail['store_marker']){
			//  marker_img = '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'gmapstrlocator/marker/'; ?>'+loc_detail['gmapstrlocator_id']+'/'+loc_detail['store_marker'];
			//}

			if(is_marker_numbers_enable == 1){

			    marker = new MarkerWithLabel({
				      position: new google.maps.LatLng(loc_detail['latitude'], loc_detail['longitude']),
				      icon:	marker_img,
				      map: map,
				      draggable: false,
				      raiseOnDrag: false,
				      labelContent: i+1,
				      labelAnchor: new google.maps.Point(4, 30),
				      labelClass: "gmap-marker-labels", // the CSS class for the label
				      labelInBackground: false
				  });
			}else{

			    marker = new google.maps.Marker({
				  position: new google.maps.LatLng(loc_detail['latitude'], loc_detail['longitude']),
				  icon:	marker_img,
				  map: map
			    });
			}



			MarkerArr[loc_detail['gmapstrlocator_id']] = marker;

			popupCreate(marker, loc_detail, i);

			google.maps.event.addListener(marker, 'click', (function(marker, i) {
				return function(){

				  for(j=0; j<PopupArr.length; j++){
				      //close all opened popups
				      if(PopupArr[j])
				      	PopupArr[j].close();
				  }
				  PopupArr[loc_detail['gmapstrlocator_id']].open(map, marker);


				}

			})(marker, i));

	}


	function popupCreate(marker, loc_detail, i) {

					var boxText ="";
					var s_distance = "";
					var s_image = "";
					var s_phone = '';
					var s_fax = '';
					var s_state= ',';
					var store_iden	=   loc_detail['store_identifier'];

					//if(stores_from_distances[i])
					  //  s_distance = '<span><b><?php echo $this->__('Distance') ?> : </b> '+stores_from_distances[i]+'</span>';

					if(loc_detail['store_image']){
					    //s_image_path = "<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'gmapstrlocator/' ?>";
					   // s_image_path = s_image_path+loc_detail['gmapstrlocator_id']+'/thumb/'+loc_detail['store_image'];
					    //s_image = "<div class='store-thumb'><img src='"+s_image_path+"'></div>";
					}
					if(loc_detail['store_phone'] != ''){
					    s_phone = '<span><b><?php echo $this->__('Phone') ?>:  </b></span> '+ loc_detail['store_phone']+'<br />';
					}
					if(loc_detail['store_fax'] != ''){
					    s_fax = '<span><b><?php echo __('Fax:  '); ?></b></span> '+ loc_detail['store_fax']+'<br />';
					}
					if(loc_detail['state'] == '' || loc_detail['state'] == null){
					    s_state = ', ';
					}else{
					    s_state = ', '+ loc_detail['state']+',';
					}

					if(store_iden != ''){
					  var detail_link = '<a class="popup-detail-link" href="<?php echo Mage::getBaseUrl().$list_url.'/'; ?>'+store_iden+'<?php echo $seo_sufix; ?>"> ...</a>';
					}else{
					  var detail_link = '<a class="popup-detail-link" href="<?php echo Mage::getUrl('gmapstrlocator/index/detail').'id/'; ?>'+loc_detail['gmapstrlocator_id']+'"> ...</a>';
					}

					if(loc_detail['store_description'].length > 150){
					    s_desc = loc_detail['store_description'].substring(0, 150)+detail_link;

					}else{
					    s_desc = loc_detail['store_description'];
					}





					boxText = document.createElement("div");
					boxText.innerHTML ='<div id="pop_div" class="map_popup_top1"><h1>'+loc_detail['store_name']+'</h1>'+ s_desc + '<div class="store-more-info">'+s_phone+s_fax+'<span><b><?php echo $this->__('Address') ?>:  </b></span> '+ loc_detail['address'] +', '+ loc_detail['postal_code']+', '+ loc_detail['district']+s_state+ loc_detail['country']+'<br />'+s_distance+'</div>'+s_image+'<div class="getting_directions"><div class="clear"></div><a onClick="calculateRoute('+ loc_detail['gmapstrlocator_id'] +')" href="#"><?php echo $direction_button_text; ?></a></div></div>';
					var box = boxText.innerHTML + '<div class="map_popup_bottom"><img src="<?php echo $popup_secondary_image; ?>" alt="" width="290px;" /></div>';

					var myOptions = {
						content: box
						,disableAutoPan: false
						,maxWidth: 0
						,pixelOffset: new google.maps.Size(-150, -320)
						,zIndex: null
						,boxStyle: {
							background: "url('<?php echo $this->getSkinUrl('images/gmapstrlocator/map_popup_top.png')?>') no-repeat"
							,opacity: 1
							,width: "295px"
							,height:"250px"
						}
						,closeBoxMargin: "-13px -5px 2px"
						,closeBoxURL: "<?php echo $this->getSkinUrl('images/gmapstrlocator/close_black.png')?>"
						,close_onmouseover :"<?php echo $this->getSkinUrl('images/gmapstrlocator/close_icon.png')?>"
						,close_onmouseout :"<?php echo $this->getSkinUrl('images/gmapstrlocator/close_black.png')?>"
						,infoBoxClearance: new google.maps.Size(1, 1)
						,isHidden: false
						,pane: "floatPane"
						,enableEventPropagation: true
					};
					var ib = new InfoBox(myOptions);
					PopupArr[loc_detail['gmapstrlocator_id']] = ib;
					//ib.open(map, marker);
				}


	function createClickObserverPopup(store_id, index){


	  if(store_id != null && index != null){

	    //first close all popups of array, then move to open the current one
	    for(j=0; j<PopupArr.length; j++){

		//close all opened popups
		PopupArr[store_id].close();
	    }



	    var popupObj = PopupArr[store_id];
	    var markerObj = MarkerArr[store_id];


	    //place OR create marker
	    if(markerObj){
		markerObj.setMap(map);
	    }else{
		//create marker
		creatmarkers(index, locations[index]);
	    }


	    //opens OR create the popup
	    if(popupObj){
		popupObj.open(markerObj, map);
	    }else{
		  //create popup
		 popupCreate(markerObj, locations[index], index);
	    }

	  }

	}



	function findDistanceFromClientToStores(to_latlng, search_radius){


			  if(to_latlng){

			    for (j = 0; j < locations.length; j++) {

				var latlng = new google.maps.LatLng(locations[j]['latitude'], locations[j]['longitude']);

				var distance_m = google.maps.geometry.spherical.computeDistanceBetween(latlng,to_latlng);
				stores_from_distances[j] = distance_m;
				locations[j]['distance'] = stores_from_distances[j];

				//var distance_km = distance_m/1000;
			    }

			    //sort locations by distance
			    locations.sort(function(a,b){return (a['distance'] < b['distance'] ? -1 : (a['distance'] > b['distance'] ? 1 : 0)); });
			    generateStoreList(search_radius);


			  }

	}


	function clientPosition(){

			  jQuery('#map_canvas').gmap({ 'zoom':<?php echo Mage::helper('gmapstrlocator')->getGMapZoom(); ?>,'center':new google.maps.LatLng(<?php echo $standard_lat; ?>,<?php echo $standard_long; ?>), 'callback': function() {

					var self = this;
					self.getCurrentPosition(function(position, status) {
						if ( status === 'OK' ) {

							clientlat = position.coords.latitude;
							clientlon = position.coords.longitude;
							var clientlatlng = new google.maps.LatLng(clientlat, clientlon);

							user_position_search = clientlatlng;
							findDistanceFromClientToStores(user_position_search);
							jQuery('#scrollbar1').tinyscrollbar_update();

						}
					});

			  }});

	}


	function showFromList(store_id){


	      unsetAllPopups();
	      unsetAllMarkers();

	      if(is_direction_on){
		initialize();
	      }

	      if(MarkerArr[store_id] && PopupArr[store_id]){
		map.setZoom(10);
		MarkerArr[store_id].setMap(map);
		PopupArr[store_id].open(map, MarkerArr[store_id]);


	      }else{
		alert(store_id);
	      }

	}

	function mouseoverFromList(store_id){


	      if(is_hover_marker_change == 1){

		if(MarkerArr[store_id]){

		    MarkerArr[store_id].setIcon(hoverIcon);

		}
	      }

	}


	function mouseoutFromList(store_id){


	      if(is_hover_marker_change == 1){

		if(MarkerArr[store_id]){

		    MarkerArr[store_id].setIcon(destinationIcon);

		}
	      }

	}


	function searchAddress(search_qry_create){




			  var qrystr = document.getElementById('s_address').value;

			      if(qrystr == '' || !qrystr || qrystr == 'Enter a location'){

				      alert('Address Required');
				      return false;
			      }
			  initialize();
			  var s_radius = document.getElementById('store_radius').value;


			      var  pgeocoder = new google.maps.Geocoder();
			      pgeocoder.geocode( { 'address': qrystr}, function(results, status) {
				    if (status == google.maps.GeocoderStatus.OK) {
					    var qryLatlng = results[0].geometry.location;
					    user_position_search = qryLatlng;
					    findDistanceFromClientToStores(user_position_search,s_radius);
					    map.setCenter(qryLatlng);
					    jQuery('#scrollbar1').tinyscrollbar_update();
				    }
			      });
	}



	function in_array(array, id) {


	      for(var i=0;i<array.length;i++) {
		  if(array[i] === id) {
		      return true;
		  }
	      }
	      return false;
	}


	function unsetAllMarkers(){


	  for(var i = 0; i<locations.length; i++){

	      if(MarkerArr[locations[i]['gmapstrlocator_id']]){

		  MarkerArr[locations[i]['gmapstrlocator_id']].setMap(null);
	      }

	  }

	    //MarkerArr.forEach(function(entry) {
		//entry.setMap(null);
	    //});
	}

	function unsetAllPopups(){


	      for(var i = 0; i<locations.length; i++){

		  if(PopupArr[locations[i]['gmapstrlocator_id']]){
		      PopupArr[locations[i]['gmapstrlocator_id']].close();
		  }

	      }

	}


	function calculateRoute(store_id) {

	    var start = '';

	    if(MarkerArr[store_id]){

	      start = user_position_search;
	      var stop = MarkerArr[store_id].getPosition();
	      getDirection(stop, start);

	    }

	}


	function getDirection(stop_latlng, start) {

	  //alert(locations[index]['store_name']);
		//var stop = detail_arr['latitude'] + ',' + detail_arr['longitude'];
		var stop = stop_latlng;
		var map;
		var directionsDisplay;
		var directionsService;
		var stepDisplay;
		var markerArray = [];

		directionsService = new google.maps.DirectionsService();

		/******  Standard Latitude and Longitude from Config  ********/

		  // Create a map and center it on Manhattan.
		  var portugal = new google.maps.LatLng(<?php echo $standard_lat; ?>,<?php echo $standard_long; ?>);
		  var myOptions = {
		    zoom: <?php echo Mage::helper('gmapstrlocator')->getGMapZoom(); ?>,
		    mapTypeId: google.maps.MapTypeId.ROADMAP,
		    center: portugal
		  }



		  map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);

		  // Create a renderer for directions and bind it to the map.
		  var rendererOptions = {
		    map: map
		  }
		  directionsDisplay = new google.maps.DirectionsRenderer(rendererOptions)

		  // Instantiate an info window to hold step text.
		  stepDisplay = new google.maps.InfoWindow();

				 // First, clear out any existing markerArray
		  // from previous calculations.
		  //for (i = 0; i < markerArray.length; i++) {
		  //  markerArray[i].setMap(null);
		  //}

		  //unsetAllMarkers();


		var request = {
		    origin:start,
		    destination:stop,
		    travelMode: google.maps.DirectionsTravelMode.DRIVING
		};
		  // Route the directions and pass the response to a
		  // function to create markers for each step.
		  directionsService.route(request, function(response, status) {
		    if (status == google.maps.DirectionsStatus.OK) {
		      //updateMessage(1 , locations[index]['district']);
			directionsDisplay.setDirections(response);
			is_direction_on = true;
			var route = response.routes[0];

			var 	href = 'saddr=';
				href +=route.legs[0].start_address;
				href +='&daddr=';
				href +=route.legs[0].end_address;
				//href +=locations[index]['postal_code'] + ' ' +locations[index]['district'] + ',' + locations[index]['country'];
				href +='&pw=2';
			var nhref ='http://maps.google.com/maps?'+href;
			var MainDiv = document.createElement('div');
			var directinControl = new DirectionControl(MainDiv, map , nhref);

			MainDiv.index = 1;
			map.controls[google.maps.ControlPosition.TOP_RIGHT].push(MainDiv);
		    }else{

			return;
		  }
		  });

	}

	function DirectionControl(maincontrolDiv, map , href) {

		maincontrolDiv.style.padding = '5px';

		var directioncontrolUI = document.createElement('div');
		directioncontrolUI.style.backgroundColor = 'white';
		directioncontrolUI.style.borderStyle = 'solid';
		directioncontrolUI.style.borderWidth = '1px';
		directioncontrolUI.style.cursor = 'pointer';
		directioncontrolUI.style.textAlign = 'center';
		directioncontrolUI.title = 'Click here to print directions';
		maincontrolDiv.appendChild(directioncontrolUI);

		var controlText = document.createElement('div');
		controlText.style.fontFamily = 'Arial,sans-serif';
		controlText.style.fontSize = '12px';
		controlText.style.padding = '2px 4px';
		controlText.innerHTML = '<strong>Print directions<strong>';
		directioncontrolUI.appendChild(controlText);

		google.maps.event.addDomListener(directioncontrolUI, 'click', function() {
		  window.open(href);
		});
	}










	function filterByAttributes(attibute_id){

	      //alert(attibute_id);
	      //check whether current filter is selected

	      if(jQuery('#filter-'+attibute_id).hasClass('selected')){ //this filter is already selected, unselect this

		//jQuery('#filter-'+attibute_id).removeClass('selected');
		//jQuery('#filter-'+attibute_id+' .close').css('display','none');

	      }else{ //add this class to the filter

		jQuery('#filter-'+attibute_id).addClass('selected');
		jQuery('#filter-'+attibute_id+' .close').css('display','block');

		filterAttributeIds.push(attibute_id);
		filterAllSelectedAttributes();
	      }

	}


	function removeFilter(attibute_id){

	  if(jQuery('#filter-'+attibute_id).hasClass('selected')){ //this filter is already selected, unselect this

		jQuery('#filter-'+attibute_id).removeClass('selected');
		jQuery('#filter-'+attibute_id+' .close').css('display','none');

		removeItem(filterAttributeIds, attibute_id);
		filterAllSelectedAttributes();
	  }

	}

	function filterAllSelectedAttributes(){

	  //firt unique the array
	  filterAttributeIds = jQuery.grep(filterAttributeIds, function(v, k){
	      return jQuery.inArray(v ,filterAttributeIds) === k;
	  });


	  //get all selected attributes
	  if(filterAttributeIds.length > 0){
	      generateStoreList(false, filterAttributeIds);
	  }else{
	      generateStoreList(false);
	  }


	}

	function removeItem(array, item){
	    for(var i in array){
		if(array[i]==item){
		    array.splice(i,1);
		    break;
		    }
	    }
	}




	function removeAllFilters(){

	  for (j = 0; j < filterAttributeIds.length; j++) {

		jQuery('#filter-'+filterAttributeIds[j]).removeClass('selected');
		jQuery('#filter-'+filterAttributeIds[j]+' .close').css('display','none');

	  }

	  filterAttributeIds.length = 0;
	  generateStoreList(false);
	}


	function generateStoreList(search_radius, attribute_filter_id){

	      unsetAllMarkers();

	      var html = '';
	      var result_found = false;

	      for (j = 0; j < locations.length; j++) {



		  // filtering store attributes --------- starts
		  if(attribute_filter_id){

		    var attr_ids_str = locations[j]['linked_attributes'];
		    if(attr_ids_str){

		      var attr_ids_arr = new Array();
		      attr_ids_arr = attr_ids_str.split(",");

		      for(i=0; i<attr_ids_arr.length; i++){ attr_ids_arr[i] = parseInt(attr_ids_arr[i]); }

		      var found = 0;
		      for(k=0; k<attribute_filter_id.length; k++){

			      if(jQuery.inArray(parseInt(attribute_filter_id[k]), attr_ids_arr) != -1){

				found++; //continue;

			      }else{

				//alert(attribute_filter_id);
			      }
		      }

		      if(found != attribute_filter_id.length){
			  continue;
		      }


		    }else{

		      continue;
		    }

		  }
		  //filtering store attributes -------- ends




		  var store_id		=   locations[j]['gmapstrlocator_id'];
		  var store_name	=   locations[j]['store_name'];
		  var store_iden	=   locations[j]['store_identifier'];
		  var address		=   locations[j]['address'];
		  var district		=   locations[j]['district'];
		  var state		=   locations[j]['state'] ? locations[j]['state'] : '';
		  var postal_code	=   locations[j]['postal_code'];
		  var country		=   locations[j]['country'];
		  var store_phone	=   locations[j]['store_phone'];
		  var store_fax		=   locations[j]['store_fax'];
		  var store_attributes	=   locations[j]['attributes_list'];
		  var distance		=   locations[j]['distance'];


		  if(map_config_distance == 'km'){

		      var new_distance_km	=   distance/1000;
		      var distance_km	=   distance/1000;
		      distance_km	=   distance_km.toFixed(2)+' km';

		  }else{
		      new_distance_km	=   distance/1609.34;
		      distance_km	=   distance/1609.34;
		      distance_km 	=   distance_km.toFixed(2)+' mile';
		  }

		  //alert(store_id);

		  var s_number = j+1;


		  if(search_radius){ // radius is in km

			  if(new_distance_km <= search_radius)    {
			    result_found = true;

				  html += '<div class="store" id="gmap-store-'+store_id+'">';

					var store_mar = '';

					if(is_marker_sidebar_enable ==1){
					  store_mar += '<img src="'+destinationIcon+'">';
					}

					if(is_marker_numbers_enable == 1 && is_marker_sidebar_enable == 1){
					  store_mar +='<div class="gmap-list-marker-labels">'+s_number+'</div>';
					}else if(is_marker_numbers_enable == 1 && is_marker_sidebar_enable != 1){
					  store_mar +='<div class="gmap-list-number-labels">'+s_number+'</div>';
					}

					html += '<a href="javascript: " onclick="showFromList('+store_id+');"  onmouseover="mouseoverFromList('+store_id+');"  onmouseout="mouseoutFromList('+store_id+');" >'+store_mar+store_name+'</a>';
					html += '<p>'+address+', '+district+', '+postal_code+' '+state+', '+country+'</p>';
					html += '<div class="left-info">';
					  if(store_phone) html += '<span> <?php echo $this->__('Phone') ?> : '+store_phone+'</span><br>';
					  if(store_fax) html += '<span> Fax : '+store_fax+'</span><br>';
					  if(distance) html += '<span> <?php echo $this->__('Distance') ?> : '+distance_km+'</span><br>';
					html += '</div>';
					html += '<div class="right-info">';
					  html += store_attributes;
					html += '</div>';

					html += '<div class="detail-link">';

					  if(store_iden != ''){
					    html += '<a href="<?php echo Mage::getBaseUrl().$list_url.'/'; ?>'+store_iden+'<?php echo $seo_sufix; ?>"><?php echo $this->__('View Detail') ?></a>';
					  }
					  else{
					    html += '<a href="<?php echo Mage::getUrl('gmapstrlocator/index/detail').'id/'; ?>'+store_id+'"><?php echo $this->__('View Detail') ?></a>';
					  }
					html += '</div>';

				  html += '<div class="clear"></div>';
				  html += '</div>';

				  creatmarkers(j, locations[j]);
			  }
		  }else{

				  html += '<div class="store" id="gmap-store-'+store_id+'">';

					var store_mar = '';

					if(is_marker_sidebar_enable ==1){
					  store_mar += '<img src="'+destinationIcon+'">';
					}

					if(is_marker_numbers_enable == 1 && is_marker_sidebar_enable == 1){
					  store_mar +='<div class="gmap-list-marker-labels">'+s_number+'</div>';
					}else if(is_marker_numbers_enable == 1 && is_marker_sidebar_enable != 1){
					  store_mar +='<div class="gmap-list-number-labels">'+s_number+'</div>';
					}

					html += '<a href="javascript: " onclick="showFromList('+store_id+');"  onmouseover="mouseoverFromList('+store_id+');"  onmouseout="mouseoutFromList('+store_id+');" >'+store_mar+store_name+'</a>';
					html += '<p>'+address+', '+district+', '+postal_code+' '+state+', '+country+'</p>';
					html += '<div class="left-info">';
					  if(store_phone) html += '<span> <?php echo $this->__('Phone') ?> : '+store_phone+'</span><br>';
					  if(store_fax) html += '<span> Fax : '+store_fax+'</span><br>';
					  if(distance) html += '<span> <?php echo $this->__('Distance') ?> : '+distance_km+'</span><br>';
					html += '</div>';
					html += '<div class="right-info">';
					  html += store_attributes;
					html += '</div>';

					html += '<div class="detail-link">';
					  if(store_iden != ''){
					    html += '<a href="<?php echo Mage::getBaseUrl().$list_url.'/'; ?>'+store_iden+'<?php echo $seo_sufix; ?>"><?php echo $this->__('View Detail') ?></a>';
					  }
					  else{
					    html += '<a href="<?php echo Mage::getUrl('gmapstrlocator/index/detail').'id/'; ?>'+store_id+'"><?php echo $this->__('View Detail') ?></a>';
					  }
					html += '</div>';


				  html += '<div class="clear"></div>';
				  html += '</div>';

				  //document.write(html);
				  creatmarkers(j, locations[j]);

		  }

	      }

	      if(search_radius && !result_found){

		document.getElementById('result').update('<div class="store"><p>No Store found</p></div>');

	      }else{

		document.getElementById('result').update(html);

	      }

	      jQuery('#scrollbar1').tinyscrollbar_update();

	}



	function createSingleStore(j){

		  var html = '';

		  var store_id		=   locations[j]['gmapstrlocator_id'];
		  var store_name	=   locations[j]['store_name'];
		  var store_iden	=   locations[j]['store_identifier'];
		  var address		=   locations[j]['address'];
		  var district		=   locations[j]['district'];
		  var state		=   locations[j]['state'] ? locations[j]['state'] : '';
		  var postal_code	=   locations[j]['postal_code'];
		  var country		=   locations[j]['country'];
		  var store_phone	=   locations[j]['store_phone'];
		  var store_fax		=   locations[j]['store_fax'];
		  var store_attributes	=   locations[j]['attributes_list'];
		  var distance		=   locations[j]['distance'];

		  var distance_km	=   distance/1000;
		      distance_km	=   distance_km.toFixed(2)+' km';

		  if(map_config_distance == 'mile'){

		      distance_km	= distance/1609.34;
		      distance_km	= distance_km.toFixed(2)+' mile';
		  }


		  var s_number = j+1;

				  html += '<div class="store" id="gmap-store-'+store_id+'">';

					var store_mar = '';

					if(is_marker_sidebar_enable ==1){
					  store_mar += '<img src="'+destinationIcon+'">';
					}

					if(is_marker_numbers_enable == 1 && is_marker_sidebar_enable == 1){
					  store_mar +='<div class="gmap-list-marker-labels">'+s_number+'</div>';
					}else if(is_marker_numbers_enable == 1 && is_marker_sidebar_enable != 1){
					  store_mar +='<div class="gmap-list-number-labels">'+s_number+'</div>';
					}

					html += '<a href="javascript: " onclick="showFromList('+store_id+');"  onmouseover="mouseoverFromList('+store_id+');"  onmouseout="mouseoutFromList('+store_id+');" >'+store_mar+store_name+'</a>';
					html += '<p>'+address+', '+district+', '+postal_code+' '+state+', '+country+'</p>';
					html += '<div class="left-info">';
					  if(store_phone) html += '<span> <?php echo $this->__('Phone') ?> : '+store_phone+'</span><br>';
					  if(store_fax) html += '<span> Fax : '+store_fax+'</span><br>';
					  if(distance) html += '<span> <?php echo $this->__('Distance') ?> : '+distance_km+'</span><br>';
					html += '</div>';
					html += '<div class="right-info">';
					  html += store_attributes;
					html += '</div>';

					html += '<div class="detail-link">';
					  if(store_iden != ''){
					    html += '<a href="<?php echo Mage::getBaseUrl().$list_url.'/'; ?>'+store_iden+'<?php echo $seo_sufix; ?>"><?php echo $this->__('View Detail') ?></a>';
					  }
					  else{
					    html += '<a href="<?php echo Mage::getUrl('gmapstrlocator/index/detail').'id/'; ?>'+store_id+'"><?php echo $this->__('View Detail') ?></a>';
					  }
					html += '</div>';


				  html += '<div class="clear"></div>';
				  html += '</div>';



				  creatmarkers(j, locations[j]);

		  document.getElementById('result').innerHTML = document.getElementById('result').innerHTML+html;
	}


	//----Search Stores By Product -----------------------------------------------------

	function searchByProducts(){

	    var search_text = jQuery('#prod_search').val();
	    var addr_text = jQuery('#s_address').val();


	    var to_latlng = '';



	    if(search_text == '' || search_text == null){

		alert('Search Contents Required');
		return false;

	    }else{

		if(addr_text != ''){

		  var search_str = addr_text;
		  var  pgeocoder = new google.maps.Geocoder();
			pgeocoder.geocode( { 'address': search_str}, function(results, status) {
					if (status == google.maps.GeocoderStatus.OK) {
						to_latlng = results[0].geometry.location;
					}
			});

		}
		//send the ajax call to index controller

		jQuery.ajax({
			type: "POST",
			url: "<?php echo $this->getUrl('gmapstrlocator/index/searchprod'); ?>",
			data: { query_string: search_text },
			dataType: "json",
			success: function(data) {

			   showStoresByLatLang(data, to_latlng);
		      }
		      });

	    }

	}


	function showStoresByLatLang(arr, to_latlng){


	    var is_matched = false;
	    initialize();
	    unsetAllMarkers();
	    document.getElementById('result').update('');

	    resulting_stores = new Array();



	    for (j = 0; j < locations.length; j++) {

		for(var i=0; i<arr.length; i++){
				var cur_latlang = arr[i]['latitude']+','+arr[i]['longitude'];
				var s_latlang = locations[j]['latitude']+','+locations[j]['longitude'];

				var latlng = new google.maps.LatLng(locations[j]['latitude'], locations[j]['longitude']);

				if(cur_latlang == s_latlang){

					    is_matched = true;
					    //resulting_stores[i] = locations[j];
					    createSingleStore(j);
				}
		}

	    }

	    //resulting_stores.sort(function(a,b){return (a['distance'] < b['distance'] ? -1 : (a['distance'] > b['distance'] ? 1 : 0)); });
	    //for (k = 0; k < resulting_stores.length; k++) {
	    //  createSingleStore(k);
	    //}



	    if(is_matched == false){

		document.getElementById('result').update('<div class="store"><p><?php echo 'No Store found'; ?></p></div>');
	    }

	    jQuery('#scrollbar1').tinyscrollbar_update();
	}





	//-------------------------Call to methods


	if(!user_position_search)
	{
	  clientPosition();
	}


	initialize();
	//showAllStores();





      </script>