<?php
	$url = Mage::helper('shopbybrand')->getShopbybrandUrl();
?>

<div class="brandscategories col">
    <div class="page-title">
            <h1><?php echo $this->__('Brand by Category') ?></h1>
    </div>
    <ul>
    <?php 
        $cats = $this->getAllCategories();
        $categories = $cats['parent'];
        $count=count($categories);
        $div = intval($count/4);
        if($count%4==3) $div++ ;
        if($count%4==1||$count%4==2) $div_more=$div+1;
        $j=0;
        $column=1;
        $i=0; 
        foreach ($categories as $category) {
            $childs = $cats['children'][$category->getId()];
            $i++;
            $j++;
    ?>
		
        <?php if($j==1): ?>
        <ol class="list_1">
        <?php endif;?>
			
            <li id="cat-<?php echo $i; ?>">
            <?php if(count($childs)>1) : ?>
                    <a class="show-child">&nbsp;</a>
            <?php endif;?>
                    <a style="<?php if(count($childs)<=1): ?>padding-left:15px;<?php endif ;?>" 
                       href="<?php echo $url.'?category='.$category->getId();?>" 
                       id="a-cat-<?php echo $category->getId();?>"
                    >
                            <?php echo $category->getName(); ?>
                    </a>
                    <?php if(count($childs)>1) : ?>
                    <ul class="brand-child">
                    <?php
                            foreach($childs as $child):
                                    if($child->getId() != $category->getId()):
                    ?>
                            <li class="child-cat">
                                    <a href="<?php echo $url.'?category='.$child->getId();?>" 
                                       id="a-cat-<?php echo $child->getId();?>"
                                    >
                                            <?php echo $child->getName(); ?>
                                    </a>
                            </li>
                    <?php endif;endforeach;?>
                    </ul>
                    <?php endif; ?>
            </li>
        <?php if($count%4==1):if($column==1):if($j==$div_more):?></ol><?php $j=0;$column++;endif;endif;endif;?>
        <?php if($count%4==1):if($column!=1):if($j==$div&&$div>0): ?></ol><?php $j=0;$column++; endif;endif;endif;?>
        <?php if($count%4==2):if($column==1||$column==2):if($j==$div_more):?></ol><?php $j=0;$column++;endif;endif;endif;?>
        <?php if($count%4==2):if($column!=1&&$column!=2):if($j==$div&&$div>0):?></ol><?php $j=0;$column++;endif;endif;endif;?>
        <?php if($count%4==3||$count%4==0): if($j==$div): ?></ol><?php $j=0;$column++;  endif;endif;?>
        <?php if($count%4==3): if($column==4):if($j==$div-1&&$div>1): ?></ol><?php endif; endif;endif;?>						
        <?php } ?>
    </ul>
    <script>
        var activeCategory = '<?php echo "a-cat-".Mage::app()->getRequest()->getParam('category')?>';
        var shbj = jQuery.noConflict();
        shbj(document).ready(function(shbj) {
            shbj('a.show-child').click(function(){	
                if(shbj(this).hasClass('child_active'))
                    shbj(this).removeClass('child_active');
                else
                    shbj(this).addClass('child_active');
                var parent_id = shbj(this).parent().attr('id');
                shbj('#'+parent_id+' .brand-child li').toggle(300,'linear');
            });	
        });
        
        shbj('#'+activeCategory).css( "color", "#000" );
        shbj('#'+activeCategory).click(function(){return false;});
        if (shbj('#'+activeCategory).parent().hasClass('child-cat')) {
            if(shbj('#'+activeCategory).parent().parent().parent().children('.show-child').hasClass('child_active'))
                shbj('#'+activeCategory).parent().parent().parent().children('.show-child').removeClass('child_active');
            else
                shbj('#'+activeCategory).parent().parent().parent().children('.show-child').addClass('child_active');
            var parent_id = shbj('#'+activeCategory).parent().parent().parent().attr('id');
            shbj('#'+parent_id+' .brand-child li').toggle(300,'linear');
        }
            
    </script>
</div>