<?php
    $store = Mage::app()->getStore()->getId();
    $display = Mage::getStoreConfig('shopbybrand/brand_detail/display_brand_featured_products', $store);
    if($display){
    $featuredProducts = $this->getFeaturedProducts();
    $showAsSlider = true;
    $logo_width = 125;
    $logo_height = 125;
    $numberOfFeaturedProducts = 0;
?>

<?php if (count($featuredProducts)):?>
<?php if (!$showAsSlider) :?>
<style type="text/css" media="screen">
    .brand-logo {
        height: 125px;
        align-items: center;
        display: inline-flex;
    }
</style>
<div class="featuredbrands col">
    <div class="page-title">
        <h1><?php echo $this->__('Featured Products');?></h1>
    </div>
    <div class="content">
        <ul>
        <?php foreach ($featuredProducts as $featuredProduct) { ?>
            <?php
                $path = 'brands/thumbnail' . DS . $featuredProduct->getId();
                $img = $this->helper('catalog/image')->init($featuredProduct, 'small_image')->resize(145, 112);
            ?>
            <li class="span_1">
                <a href="<?php echo $this->getProductUrl($featuredProduct); ?>">
                    <div class="brand-logo">
                        <img src="<?php echo $img; ?>" />
                    </div>
                    <div style="display: block;">
                    <?php echo $featuredProduct->getName(); ?>
                    </div>
                </a>
            </li>
        <?php } ?>
        </ul>
    </div>
</div>
<?php else:?>

<script language="javascript" src="<?php echo $this->getSkinUrl('css/shopbybrand/templates/default/jquery.min.js')?>"></script>
<script language="javascript" src="<?php echo $this->getSkinUrl('css/shopbybrand/templates/default/jquery.easing.1.3.js'); ?>"> </script>
<script language="javascript" src="<?php echo $this->getSkinUrl('css/shopbybrand/templates/default/jquery.mousewheel.js'); ?>"> </script>
<script language="javascript" src="<?php echo $this->getSkinUrl('css/shopbybrand/templates/default/jquery.contentcarousel.js'); ?>"> </script>

<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/shopbybrand/templates/default/freaturedproductsiliderstyle.css'); ?>" media="all" />

<?php if ($numberOfFeaturedProducts == 5) :?>
<style type="text/css" media="screen">
    @media screen and (min-width: 1200px) {
        .ca-container{
            width:1100px;
            
        }
    }
</style>
<?php endif;?>

<?php if ($numberOfFeaturedProducts == 6) :?>
<style type="text/css" media="screen">
    @media screen and (min-width: 1200px) and (max-width: 1439px) {
        .ca-container{
            width:1100px;
        }
    }
    @media screen and (min-width: 1440px) {
        .ca-container{
            width:1320px;
        }
    }
</style>
<?php endif;?>



<div class="featuredbrands col" style="padding: 0;">
    <div class="page-title">
        <h1><?php echo $this->__('Featured Products');?></h1>
    </div>
    <div id="ca-container" class="ca-container">
        <div class="ca-wrapper">
            <?php 
                $i = 0;
                $stock = Mage::getModel('cataloginventory/stock_item');
                foreach ($featuredProducts as $featuredProduct) : 
                    $max_available_quantity = (int)$stock->loadByProduct($featuredProduct)->getQty();
                    if($featuredProduct->getStockItem()->getIsInStock()&&($max_available_quantity>0)){
                    $i++;
                    $path = 'brands/thumbnail' . DS . $featuredProduct->getId();
                    $img = $this->helper('catalog/image')->init($featuredProduct, 'small_image')->resize(145, 112);
            ?>
            <div class="ca-item ca-item-<?php echo $i;?>">
                <div class="ca-item-main">
                    <a href="<?php echo $this->getProductUrl($featuredProduct); ?>">
                        <div class="brand-logo" style="margin-bottom: 5px;margin-bottom: 5px;">
                            <img src="<?php echo $img; ?>" />
                        </div>
                        <div style="display: block;">
                        <?php echo $featuredProduct->getName(); ?>
                        </div>
                    </a>
                </div>
            </div>
            <?php 
                    }
                endforeach;
            ?>
        </div>
    </div>
    <script type="text/javascript">
        var fb = jQuery.noConflict();
        var numberfeaturedproduct = <?php echo $i; ?>;
        var featuredbrandsWidth = fb('.featuredbrands').innerWidth()-50;
        var numberofbrand = Math.floor(featuredbrandsWidth/170);
        numberofbrand = (numberfeaturedproduct < numberofbrand)?numberfeaturedproduct:numberofbrand;
        fb('#ca-container').css('width',numberofbrand*170);
        
        window.onresize = resize;
        function resize()
        {
            var featuredbrandsWidth = fb('.featuredbrands').innerWidth()-50;
            var numberofbrand = Math.floor(featuredbrandsWidth/170);
            numberofbrand = (numberfeaturedproduct < numberofbrand)?numberfeaturedproduct:numberofbrand;
            fb('#ca-container').css('width',numberofbrand*170);
        }
        fb('#ca-container').contentcarousel();
    </script>
</div>
<?php endif; ?>
<?php endif; ?>
    <?php } ?>
