<?php 
    $brand = $this->getBrand();
    if($brand->getId()):
?>
<!--edit by viet -->
<a style="float:left;width:100%" href="<?php echo $this->getUrl($brand->getUrlKey());?>">
    <?php
        if($brand->getImage()|| $brand->getThumbnailImage())
		{
            //$path = 'brands' . DS . $brand->getId();
            $path = 'brands' . DS . 'thumbnail'.DS.$brand->getId();
            $imgSrc = Mage::helper('shopbybrand/image')->init($brand, $path)->resizeThumbnail(200, 100);
            ?>
                <img src="<?php echo $imgSrc;?>" title="<?php echo $brand->getName();?>"/>
            <?php
		}
    ?>
    <!--<p>
        <?php echo $brand->getName();?>
    </p> -->
</a>
<?php endif; ?>
