<script language="javascript" src="<?php echo $this->getSkinUrl('css/shopbybrand/templates/default/jquery.js');?>"></script>
<script language="javascript" src="<?php echo $this->getSkinUrl('css/shopbybrand/templates/default/jquery-ui-autocomplete.js');?>"></script>
<script language="javascript" src="<?php echo $this->getSkinUrl('css/shopbybrand/templates/default/jquery.select-to-autocomplete.min.js');?>"></script>

<script type="text/javascript" charset="utf-8">
    function isValidURL(url){
        var RegExp = /(ftp|http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/;
        if(RegExp.test(url)){
            return true;
        }else{
            return false;
        }
    } 
    var sb = jQuery.noConflict();
    sb(document).ready(function(sb) {
        sb('#brand_instantsearch_input').selectToAutocomplete();
        sb('#brand_instantsearch_form').submit(function(){
            sb('.ui-autocomplete-input').attr("value", "Not Found!");
//            sb('#default_option').html("Not Found!");
            return false;
        });
    });
</script>
	
<style type="text/css" media="screen">
    body {
        font-family: Arial, Verdana, sans-serif;
        font-size: 13px;
    }
    .ui-autocomplete {
        padding: 0;
        list-style: none;
        background-color: #fff;
        width: 200px;
        border: 1px solid #B0BECA;
        max-height: 300px;
        overflow-y: scroll;
    }
    .ui-autocomplete .ui-menu-item a {
        border-top: 1px solid #B0BECA;
        display: block;
        padding: 3px 5px;
        text-align: left;
        color: #353D44;
        cursor: pointer;
        text-decoration: blink;
    }
    .ui-autocomplete .ui-menu-item:first-child a {
        border-top: none;
    }
    .ui-autocomplete .ui-menu-item a.ui-state-hover {
        background-color: #D5E5F4;
        color: #161A1C;
    }
    .ui-autocomplete-input {
        line-height: 1.5;
        width: 67%;
    }
    
    #brand_instantsearch_form {
        display: inline-block;
        vertical-align: top;
        width: 95%;
        border: 1px solid #CCCCCC;
    }
    #brand_instantsearch_form .form-search {
        width: 100%;
    }
    #brand_instantsearch_form .input-text {
        float: left;
        height: 30px;
        line-height: 30px;
        padding: 0 2%;
        margin: 0px;
        border: none;
        box-shadow: none;
		background: none;
    }
    #brand_instantsearch_form button.button {
        height: 30px;
        width: 30px;
        padding: 0px;
        margin: 0px 0px 0px 5px;
        float: right;
        opacity: 0.3;
        pointer-events: none;
    }
    #brand_instantsearch_form button.button span {
        height: 30px;
        width: 30px;
        padding: 0px;
        margin: 0px;
        border: none;
    }
    #brand_instantsearch_form button.button span span {
        height: 30px;
        line-height: 30px;
        padding: 0px;
        margin: 0px;
        display: none;
    }
</style>

<div id="searchbox" class="searchbox clearer">
    <form id="brand_instantsearch_form" method="post" >
        <div class="form-search">
            <select name="brand_select" 
                    id="brand_instantsearch_input" 
                    class="input-text"
                    autofocus="autofocus" autocorrect="off" autocomplete="off"
                    onchange="
                        if(isValidURL(sb(this).attr('value')))
                            sb(window.location).attr('href', sb(this).attr('value'));" 
                    onfocus="this.value = '';" 
                    onblur = "sb('#default_option').html('Search by brand name');"
            >
                <option id="default_option" value="" selected="selected"><span>Search by brand name</span></option>
                <?php foreach ($this->getAllBrands() as $brand) : ?>
                <option value="<?php echo $this->getUrl($brand->getUrlKey(), array());?>"><?php echo $brand->getData('name');?></option>
                <?php endforeach;?>
            </select>
            <button class="button" title="Search" type="submit" style="">
                <span>
                    <span>Search</span>
                </span>
            </button>
        </div>    
    </form>
</div>
<script type="text/javascript" charset="utf-8">
    sb(document).ready(function(sb) {
        sb('.ui-autocomplete-input').attr("placeholder", "Type a name");
    });
</script>